---
# DATASETS
datasets:
  extractive:
    mrqa:
      - SQuAD
      - NewsQA
      - HotpotQA
      - SearchQA
      - NaturalQuestionsShort
      - TriviaQA-web
    others:
      - QAMR
      - DuoRC

  multiple_choice:
    - SIQA
    - RACE
    - BoolQ
    - HellaSWAG
    - CommonSenseQA

  abstractive:
    - DROP
    - NarrativeQA

  multimodal:
    - HybridQA


# AGENTS
agents2training_dataset:
  # extractive
  spanbert-large-cased_DuoRC: DuoRC
  spanbert-large-cased_QAMR: QAMR
  spanbert-large-cased_HotpotQA: HotpotQA
  spanbert-large-cased_NewsQA: NewsQA
  spanbert-large-cased_NaturalQuestionsShort: NaturalQuestionsShort
  spanbert-large-cased_SearchQA: SearchQA
  spanbert-large-cased_SQuAD: SQuAD
  spanbert-large-cased_TriviaQA-web: TriviaQA-web
  # multiple_choice
  lewtun_bert-large-uncased-wwm-finetuned-boolq: BoolQ
  danlou-albert-xxlarge-v2-finetuned-csqa: CommonSenseQA
  prajjwal1-roberta_hellaswag: HellaSWAG
  roberta-large_SIQA: SIQA
  LIAMF-USP_roberta-large-finetuned-race: RACE
  # abstractive
  TASE: DROP
  bart_adapter_narrativeqa: NarrativeQA
  # multimodal
  hybrider: HybridQA


# PAHTS
paths:
  agents_path: ./qa_agents
  output_path: ./MetaQA_models
  train_data_path: /ukp-storage-1/khammari/QA-Verification-Via-NLI/MetaQA2/training/Bert5KPerAgent/nq-nli-5K-triviaQA+SearchQA.jsonl
  dev_data_path: /ukp-storage-1/khammari/QA-Verification-Via-NLI/MetaQA2/evaluation/correctDev-TriviaQA.jsonl
  test_data_path: ./data/test

model_config:
  num_epochs: 1
  eval_every: 400
